#!/bin/bash
echo "🔵 Deploying Blue version..."
kubectl apply -f messaging_app/blue_deployment.yaml

echo "🟢 Deploying Green version..."
kubectl apply -f messaging_app/green_deployment.yaml

echo "📜 Applying service..."
kubectl apply -f messaging_app/kubeservice.yaml

echo "🧾 Checking logs for Green version..."
kubectl logs -l app=messaging-green
